{ Start Job wf_VULNERABILITY_DATA at Sun Nov 18 17:45:02 CET 2018
User Current Path: /home/undpccca/etl/wf_VULNERABILITY_DATA
Project name: CAMCLIMATE | Job name: Lib_ContextReader: context will be loaded from sub folder ./context/wf_VULNERABILITY_DATA.CAMCLIMATE_PROD.cfg
.----------------------+-----------------------------------------------------------------.
|                                   Context Parameters                                   |
|=---------------------+----------------------------------------------------------------=|
|key                   |value                                                            |
|=---------------------+----------------------------------------------------------------=|
|MySQL_Server          |localhost                                                        |
|MySQL_Database        |zadmin_zbiundpccca                                               |
|MySQL_Port            |3306                                                             |
|MySQL_Login           |zbiundpccca                                                      |
|MySQL_AdditionalParams|noDatetimeStringSync=true&useUnicode=true&characterEncoding=UTF-8|
|P_DATE_format         |dd-MMM-yyyy                                                      |
|P_Timestamp_format    |yyyy-MM-dd HH:mm:ss                                              |
|P_Default_String      |#                                                                |
|P_Default_Number      |0                                                                |
|P_Default_Date_String |01-Jan-1000                                                      |
|P_Default_Date_ID     |10000101                                                         |
'----------------------+-----------------------------------------------------------------'

===> Start Job m_cdb_s_village_data_frp at Sun Nov 18 17:45:02 CET 2018
Exception in component tDBConnection_2 (m_cdb_s_village_data_frp)
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1112)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2506)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at routines.system.SharedDBConnection.getConnection(SharedDBConnection.java:63)
	at routines.system.SharedDBConnection.getDBConnection(SharedDBConnection.java:131)
	at camclimate.m_cdb_s_village_data_frp_0_1.m_cdb_s_village_data_frp.tDBConnection_2Process(m_cdb_s_village_data_frp.java:1624)
	at camclimate.m_cdb_s_village_data_frp_0_1.m_cdb_s_village_data_frp.runJobInTOS(m_cdb_s_village_data_frp.java:15326)
	at camclimate.m_cdb_s_village_data_frp_0_1.m_cdb_s_village_data_frp.runJob(m_cdb_s_village_data_frp.java:15066)
	at camclimate.wf_vulnerability_data_0_1.wf_VULNERABILITY_DATA.tRunJob_3Process(wf_VULNERABILITY_DATA.java:2115)
	at camclimate.wf_vulnerability_data_0_1.wf_VULNERABILITY_DATA.tRunJob_1Process(wf_VULNERABILITY_DATA.java:1642)
	at camclimate.wf_vulnerability_data_0_1.wf_VULNERABILITY_DATA.tJava_1Process(wf_VULNERABILITY_DATA.java:842)
	at camclimate.wf_vulnerability_data_0_1.wf_VULNERABILITY_DATA$2.run(wf_VULNERABILITY_DATA.java:6375)
=== End Job m_cdb_s_village_data_frp at Sun Nov 18 17:45:02 CET 2018
Exception in component tRunJob_3 (wf_VULNERABILITY_DATA)
java.lang.RuntimeException: Child job running failed.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
	at camclimate.wf_vulnerability_data_0_1.wf_VULNERABILITY_DATA.tRunJob_3Process(wf_VULNERABILITY_DATA.java:2132)
	at camclimate.wf_vulnerability_data_0_1.wf_VULNERABILITY_DATA.tRunJob_1Process(wf_VULNERABILITY_DATA.java:1642)
	at camclimate.wf_vulnerability_data_0_1.wf_VULNERABILITY_DATA.tJava_1Process(wf_VULNERABILITY_DATA.java:842)
	at camclimate.wf_vulnerability_data_0_1.wf_VULNERABILITY_DATA$2.run(wf_VULNERABILITY_DATA.java:6375)
End Job wf_VULNERABILITY_DATA at Sun Nov 18 17:45:02 CET 2018  }
